# Generated by Django 4.0.1 on 2022-02-01 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('areas', models.CharField(max_length=120)),
                ('workout_type', models.CharField(choices=[('PU', 'Push'), ('PL', 'Pull'), ('LG', 'Legs')], default='PU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=120)),
                ('tips', models.CharField(max_length=120)),
                ('sets', models.IntegerField(default=4)),
                ('reps', models.IntegerField(default=10)),
                ('iso_hold', models.IntegerField(default=7)),
                ('max', models.IntegerField(default=0)),
                ('order_in_workout', models.IntegerField(default=0)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
        ),
    ]
