# Generated by Django 4.0.1 on 2022-02-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_rename_exercise_log_exercise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tips',
            field=models.TextField(),
        ),
    ]
