# Generated by Django 4.0.1 on 2022-02-25 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_exercise_id_alter_log_id_alter_workout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutcalendarlog',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_cal_logs', to='workouts.workout'),
        ),
    ]
